version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8088:8088"
    depends_on:
      - chroma
#      - postgres
    environment:
      - CHROMA_HOST=chroma
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8080:8000"
    volumes:
      - ./chroma-data:/chroma/chroma
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

#  postgres:
#    image: postgres:13
#    environment:
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    restart: unless-stopped

  pg_admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pg_admin-data:/var/lib/pgadmin
    ports:
      - "8018:80"
#    depends_on:
#      - postgres
    restart: always

volumes: {}
