version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8088:8088"
    depends_on:
      - redis
      - chroma
    environment:
      - REDIS_HOST=redis
      - CHROMA_HOST=chroma
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8080:8000"
    volumes:
      - chroma-data:/chroma/chroma
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  chroma-data: